name: Deploy Zensical to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps:deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Zensical
        uses: cloudcannon/zensical-action@v1

      # This step explicitly uploads Zensical's compiled folder
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./site" # If Zensical uses a different folder like 'dist', change this to './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
